config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true, length: {maximum: 200}
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resorce)
    user_path(resorce.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.all.order(created_at: :asc)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all.order(created_at: :asc)
      render :index
    end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = 'You have destroyed book successfully.'
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  # before_action
  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save

    path = Rails.application.routes.recognize_path(request.referer)
    if path[:action] == "show"
      redirect_to book_path(book)
    else
      redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy

    path = Rails.application.routes.recognize_path(request.referer)
    if path[:action] == "show"
      redirect_to book_path(book)
    else
      redirect_to books_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all.order(created_at: :asc)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
     else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  # before_action
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<!-- エラーメッセージ -->

<% if book.errors.any? %>
  <div id="error_explanation">
    <h3><%= book.errors.count %> errors prohibited this book from being saved:</h3>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_new.html.erb
<!-- 新規投稿 -->

<h2>New book</h2>
<%= form_for(book) do |f| %>

  <div class="field row">
    <label for="book_title">Title</label><br>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>
  <div class="field row">
    <label for="body_title">Opinion</label><br>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>
  <div class="field row">
    <%= f.submit 'Create Book', class: "col-xs-12 btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<!-- Editing Book -->

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>

    <%= render 'books/error', book: @book %>

    <%= form_for(@book) do |f| %>
      <div class="field row">
        <label for="book_title">Title</label><br>
        <%= f.text_field :title, class: "col-xs-12"%>
      </div>
      <div class="field row">
        <label for="body_title">Opinion</label><br>
        <%= f.text_area :body, class: "col-xs-12" %>
      </div>
      <div class="actions row">
        <%= f.submit 'Update Book', class: "col-xs-12 btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<!-- Books -->

<%= render 'books/error', book: @book %>

<!-- サイドバー -->

<div class="row">
  <div class="col-xs-3">

    <%= render 'users/user_info' %>
    <%= render 'books/new', book: @book %>

  </div>

  <!-- 投稿一覧 -->

  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <span><%= book.title %></span>
            <% end %>
          </td>
          <td><%= book.body %></td>
          <% if book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(book), method: :delete do %>
              <i class="fa fa-heart" area-hidden="true" style="color: red;"></i>
              <%= book.favorites.count %>
            <% end %>
          </td>
          <% else %>
          <td>
            <%= link_to book_favorites_path(book), method: :post do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= book.favorites.count %>
            <% end %>
          </td>
          <% end %>
          <td>
            <p>コメント数：<%= book.book_comments.count %></p>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<!-- Books Detail -->

<!-- サイドバー -->

<div class="row">
  <div class="col-xs-3">

    <h2>User info</h2>
    <table class="table">
      <tbody>
        <tr><%= attachment_image_tag @books.user, :profile_image, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size: "100x100" %>
        </tr>
      <tr>
        <th>name</th>
        <th><%= @books.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @books.user.introduction %></th>
      </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to edit_user_path(@books.user.id), class: "col-xs-12 btn btn-default" do %>
        <span class="glyphicon glyphicon-wrench"></span>
      <% end %>
    </div>

    <%= render 'books/new', book: @book %>

  </div>

  <!-- 投稿詳細 -->

  <div class="col-xs-9">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@books.user) do %>
              <%= attachment_image_tag @books.user, :profile_image, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg", size: "40x40" %>
                <br>
                <%= @books.user.name %>
            <% end %>
          </td>
          <td><%= @books.title %></td>
          <td><%= @books.body %></td>
          <td>
            <% if @books.user == current_user %>
              <%= link_to "Edit", edit_book_path, class: "btn-sm btn-success" %>
            <% end %>
          </td>
          <td>
            <% if @books.user == current_user %>
              <%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に消しますか?", class: "btn-sm btn-danger" %>
            <% end %>
          </td>
          <% if @books.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(@books), method: :delete do %>
              <i class="fa fa-heart" area-hidden="true" style="color: red;"></i>
              <%= @books.favorites.count %>
            <% end %>
          </td>
          <% else %>
          <td>
            <%= link_to book_favorites_path(@books), method: :post do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= @books.favorites.count %>
            <% end %>
          </td>
          <% end %>
          <td>
            <p>コメント数：<%= @books.book_comments.count %></p>
          </td>
        </tr>
      </tbody>
    </table>

    <ol>
      <% @books.book_comments.each do |book_comment| %>
        <li class="clearfix">

          <div class="comment-user">
            <%= link_to user_path(book_comment.user) do %>
              <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', class: "profile-img pull-left", fallback: "no_image.jpg", size: "40x40" %>
              <br>
              <%= book_comment.user.name %>
            <% end %>
          </div>
          <div class="comment-entry"><%= book_comment.comment %></div>

          <% if book_comment.user == current_user %>
          <div class="comment-destroy">
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn-sm btn-danger btn-destroy" %>
          </div>
          <% end %>

        </li>
      <% end %>
    </ol>

    <%= form_for [@books, @book_comment] do |f| %>
      <div class="row">
        <div class="col-sm-12">
          <%= f.text_area :comment, rows:'5', class: "form-control" %>
        </div>
      </div>
      <%= f.submit "送信する", class: "btn btn-sm btn-base-1 mt-20 pull-right" %>
    <% end %>

  </div>
</div>

app/views/home/about.html.erb
<!-- About -->

<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>

app/views/home/top.html.erb
<!-- Top page -->

<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong>  !!</span></h1>
    <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>
    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f039f1073f.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <a class="glyphicon glyphicon-user users" href="/users"> Users</a>
              </li>
              <li>
                <a class="glyphicon glyphicon-book books" href="/books"> Books</a>
              </li>
              <li>
                <a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a>
              </li>
            <% else %>
              <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
              <li><a class="glyphicon glyphicon-link about" href="/home/about"> About</a></li>
              <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a></li>
              <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <div class="body">
      <div class="container">
        <p id="notice"></p>

        <%= yield %>

      </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<table class="table">
  <tbody>
    <tr><%= attachment_image_tag current_user, :profile_image, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size: "100x100" %>
    </tr>
  <tr>
    <th>name</th>
    <th><%= current_user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= current_user.introduction %></th>
  </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(current_user.id), class: "col-xs-12 btn btn-default" do %>
    <span class="glyphicon glyphicon-wrench"></span>
  <% end %>
</div>

app/views/users/edit.html.erb
<!-- Editing User -->

<h2>User info</h2>

<%= render 'books/error', book: @user %>

<%= form_for(@user) do |f| %>
  <div class="field">
    <label for="user_name">Name</label>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label for="user_image">Image</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  </div>
  <div class="field">
    <label for="user_introduction">Introduction</label>
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.submit 'Update User' %>
  </div>
<% end %>

app/views/users/index.html.erb
<!-- Users -->

<!-- サイドバー -->

<div class="row">
  <div class="col-xs-3">

    <%= render 'users/user_info' %>
    <%= render 'books/new', book: @book %>

  </div>

  <!-- ユーザー一覧 -->

  <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<!--　Home  -->

<!-- サイドバー -->

<div class="row">
  <div class="col-xs-3">

    <h2>User info</h2>
    <table class="table">
      <tbody>
        <tr><%= attachment_image_tag @user, :profile_image, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size: "100x100" %>
        </tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to edit_user_path(@user.id), class: "col-xs-12 btn btn-default" do %>
        <span class="glyphicon glyphicon-wrench"></span>
      <% end %>
    </div>

    <%= render 'books/new', book: @book %>

  </div>

  <!-- 投稿一覧 -->

  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <span><%= book.title %></span>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>